# Generated by Django 5.0.6 on 2025-08-29 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="purchased_at",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Дата покупки"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Дата"
            ),
        ),
    ]
